import Tokenizer from "./tokenizer.ts";
import ASTGen from "./ast.ts";
import Compiler from "./compiler_a.ts";
import { PC } from "../pc.ts";
const dirname = import.meta.dirname+'/';
const input = Deno.readTextFileSync(dirname+(Deno.args[0]??'test.e'))
const pc = new PC()

const tokenizer = new Tokenizer(input);
const tokens = tokenizer.tokenize();

// console.log(tokens)

const astGenerator = new ASTGen(tokens);

let ast;
try {
    ast = astGenerator.parse()
} catch (error) {
    console.error(error);
    console.log('at', astGenerator.position, tokens.map((a, i) => i == astGenerator.position ? `${a.type}(${a.value}) <--` : `${a.type}(${a.value})`).join('\n'))
    Deno.exit(1)
}

// console.log(ast)

const compiler = new Compiler(ast);

compiler.functions_start += 5

for (const node of compiler.AST) {
    compiler.compile(node)
}

const instructions: string[] = [`;; this file has been generated by the e compiler`,
`;; at ${new Date()}`];
//instructions.push('.aa 0')
instructions.push('__init__:')
instructions.push(...compiler.str_instructions)
//instructions.push('mov a [__init__]')
//instructions.push('jmp a')
instructions.push('mov a [_fn__start]')
instructions.push('jmr a')
if (compiler.functions.___exit) {
	instructions.push(...compiler.functions.___exit)
	delete compiler.functions.___exit
}
instructions.push('halt')
for (const name in compiler.functions) {
	//console.log(compiler.functions[name])
	instructions.push(...compiler.functions[name])
}
instructions.push('halt')
//instructions[0].args.push(end+0x8001)

Deno.writeTextFileSync(dirname+'ast.json', JSON.stringify(ast, null, 4))
Deno.writeTextFileSync(dirname+'depths.json', JSON.stringify(compiler.depth, null, 4))
//Deno.writeTextFileSync(dirname+'code.txt', compiler.instructions
//    .map((i, idx) => `${' '.repeat(compiler.depth[idx])}${compiler.comments[idx] ? '; ' + compiler.comments[idx] + '\n ' : ''}\
// ${i.opcode}${i.args.length > 0 ? ' ' : ''}${i.args.join(',')}`).join('\n'))
//const bin = Uint8Array.from(instructions.map<number[]>(i => {
//    const goog = Object.entries(pc.instructions).find(([_, opc]) => opc == i.opcode);
//    if (!goog) throw 'whar';
//    // console.log(goog, i)
//    return [+goog[0], 0, ...(i.args.map((a) => [a & 0x00FF, (a & 0xFF00) >> 8])).flat()]
//}).reduce<number[]>((p, c) => {p.push(...c);return p}, [] as number[]));
//Deno.writeFileSync(dirname+'../iram.bin', bin)
//Deno.writeFileSync(dirname+'./prog.bin', bin)
Deno.writeTextFileSync('code.a', instructions.join('\n'))
